import Head from "next/head";

import { useState } from "react";
import Airpods from "../components/Airpods";
import AppleWatch from "../components/AppleWatch";
import GroupWatch from "../components/GroupWatch";
import Hero from "../components/Hero";
import Iphone14 from "../components/Iphone14";
import Navbar from "../components/Navbar";
import NormalPods from "../components/NormalPods";
import Watch from "../components/Watch";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  console.log(isOpen);
  const openSidebar = () => {
    setIsOpen(!isOpen);
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      {/* Navbar */}
      <Navbar openSidebar={openSidebar} isOpen={isOpen} />
      {/* Hero */}
      <Hero />
      {/* IphoneSection*/}
      <Iphone14 />
      <AppleWatch />
      <div className="md:flex md:space-x-4  ">
        <Airpods />
        <Watch />
      </div>
      <div className="md:flex md:space-x-4 md:-mt-28 ">
        <GroupWatch />
        <NormalPods />
      </div>
    </div>
  );
}
